(() => {
  "use strict";

  const state = {
    requireClickAndDrag: false,
    difficulty: "normal",
    ready: false
  };

  function parseBoolean(
    value,
    fallback = false
  ) {
    if (
      value === true ||
      value === "true"
    ) {
      return true;
    }

    if (
      value === false ||
      value === "false"
    ) {
      return false;
    }

    return fallback;
  }

  window.clambakeInputMode = {
    requiresClickAndDrag() {
      return state.requireClickAndDrag;
    },

    cursorMode() {
      return !state.requireClickAndDrag;
    },

    difficulty() {
      return state.difficulty;
    },

    speedMultiplier() {
      return state.difficulty === "easy" ? 0.65 : 1;
    },

    isReady() {
      return state.ready;
    }
  };

  async function load() {
    try {
      const response =
        await fetch(
          "/api/settings",
          {
            cache: "no-store"
          }
        );

      if (response.ok) {
        const settings =
          await response.json();

        state.difficulty =
          settings.clambakeAdventureDifficulty === "easy"
            ? "easy"
            : "normal";

        state.requireClickAndDrag =
          parseBoolean(
            settings.clambakeAdventureRequireClickAndDrag,
            false
          );
      }
    }
    catch {
      state.difficulty = "normal";
      state.requireClickAndDrag =
        false;
    }

    state.ready =
      true;

    document.documentElement
      .classList.toggle(
        "clambake-requires-drag",
        state.requireClickAndDrag
      );

    document.documentElement
      .classList.toggle(
        "clambake-cursor-mode",
        !state.requireClickAndDrag
      );

    window.dispatchEvent(
      new CustomEvent(
        "clambake-input-mode-ready",
        {
          detail: {
            requireClickAndDrag:
              state.requireClickAndDrag,
            difficulty: state.difficulty
          }
        }
      )
    );
  }


  /* =======================================================
     CLAMBAKE TRACKPAD GUIDE CONTROLLER
     Follow the real pointer and show click/press state.
     ======================================================= */

  function setupClambakeTrackpadGuide() {
    const scene =
      document.getElementById(
        "clambakeTrackpadScene"
      );

    const leftHand =
      document.getElementById(
        "clambakeTrackpadLeftHand"
      );

    const rightHand =
      document.getElementById(
        "clambakeTrackpadRightHand"
      );

    const pressIndicator =
      scene
        ? scene.querySelector(
            ".imported-trackpad-press-indicator"
          )
        : null;

    if (
      !window.trackpadGuide ||
      !scene ||
      !leftHand ||
      !rightHand
    ) {
      return;
    }

    const controller =
      window.trackpadGuide.create({
        scene,
        leftHand,
        rightHand,
        pressIndicator,
        togglePressIndicator:
          true,
        pointerSpace:
          "viewport"
      });

    if (!controller) {
      return;
    }

    if (
      typeof controller.initialize ===
        "function"
    ) {
      controller.initialize();
    }

    document.addEventListener(
      "pointermove",
      (event) => {
        if (
          typeof controller
            .updateFromPointerEvent ===
            "function"
        ) {
          controller
            .updateFromPointerEvent(
              event
            );
        }
      }
    );

    document.addEventListener(
      "pointerdown",
      (event) => {
        // Ignore artificial pickup events generated by Clambake.
        // Only real physical presses should animate the guide.
        if (!event.isTrusted) {
          return;
        }
        if (
          typeof controller
            .updateFromPointerEvent ===
            "function"
        ) {
          controller
            .updateFromPointerEvent(
              event
            );
        }

        if (
          typeof controller.setPressed ===
            "function"
        ) {
          controller.setPressed(
            true
          );
        }
      }
    );

    document.addEventListener(
      "pointerup",
      (event) => {
        if (
          typeof controller
            .updateFromPointerEvent ===
            "function"
        ) {
          controller
            .updateFromPointerEvent(
              event
            );
        }

        if (
          typeof controller.setPressed ===
            "function"
        ) {
          controller.setPressed(
            false
          );
        }
      }
    );

    document.addEventListener(
      "pointercancel",
      () => {
        if (
          typeof controller.setPressed ===
            "function"
        ) {
          controller.setPressed(
            false
          );
        }
      }
    );

    window.addEventListener(
      "blur",
      () => {
        if (
          typeof controller.setPressed ===
            "function"
        ) {
          controller.setPressed(
            false
          );
        }
      }
    );
  }
  setupClambakeTrackpadGuide();

  load();
})();